// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhzYoH4IZQh0hvkc4uc4JE6-CXr18-Ok',
    appId: '1:691269447571:web:d3916cf877907492fcc266',
    messagingSenderId: '691269447571',
    projectId: 'ecommerce-7d93e',
    authDomain: 'ecommerce-7d93e.firebaseapp.com',
    storageBucket: 'ecommerce-7d93e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHp0tfSoND5F8fy2hpyzvPlkvzd4yyPs',
    appId: '1:691269447571:android:4c92fceb1b93576bfcc266',
    messagingSenderId: '691269447571',
    projectId: 'ecommerce-7d93e',
    storageBucket: 'ecommerce-7d93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGE0D3CyenWSw2qBoLrhHR2_xCwUdd0KQ',
    appId: '1:691269447571:ios:f592b883cab6f859fcc266',
    messagingSenderId: '691269447571',
    projectId: 'ecommerce-7d93e',
    storageBucket: 'ecommerce-7d93e.appspot.com',
    iosClientId: '691269447571-dsedjbs2ucjgqi48vmngujfujqsl3fsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
